version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_URI: mongodb://db
      JWT_SECRET: This is not the real secret
  db:
    image: mongo:latest