version: '2'
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://coronao:coronao@postgres/coronao
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: coronao
      POSTGRES_DB: coronao
      POSTGRES_PASSWORD: coronao
