version: '2'
services:
  app:
    build: .
    command: npm run debug
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    environment:
      DB_URI: mongodb+srv://wonejo:quienteconoce@braodb-dp8uh.gcp.mongodb.net/brao
      JWT_SECRET: This is not the real secret
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: coronao
      POSTGRES_DB: coronao
      POSTGRES_PASSWORD: coronao
