version: '3'
services:
  app:
    build: .
    command: npm run debug
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      DB_URI: mongodb://db
      JWT_SECRET: Thiglobal.s is not the real secret
  db:
    image: mongo:latest